removed bitnami to check pull issue

diff --git a/Docker/agents/secure-agent/dockerfile b/Docker/agents/secure-agent/dockerfile
--- a/Docker/agents/secure-agent/dockerfile
+++ b/Docker/agents/secure-agent/dockerfile
@@ -1,26 +1,6 @@
-# The MIT License
-#
-#  Copyright (c) 2015-2024, CloudBees, Inc. and other Jenkins contributors
-#
-#  Permission is hereby granted, free of charge, to any person obtaining a copy
-#  of this software and associated documentation files (the "Software"), to deal
-#  in the Software without restriction, including without limitation the rights
-#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#  copies of the Software, and to permit persons to whom the Software is
-#  furnished to do so, subject to the following conditions:
-#
-#  The above copyright notice and this permission notice shall be included in
-#  all copies or substantial portions of the Software.
-#
-#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-#  THE SOFTWARE.
 ARG DEBIAN_RELEASE=bookworm-20240812
 FROM debian:"${DEBIAN_RELEASE}"-slim as jre-build
+# FROM bitnami/minideb as jre-build
 
 SHELL ["/bin/bash", "-e", "-u", "-o", "pipefail", "-c"]
 
@@ -30,15 +10,14 @@ ARG TARGETPLATFORM
 
 COPY jdk-download-url.sh /usr/bin/local/jdk-download-url.sh
 COPY jdk-download.sh /usr/bin/local/jdk-download.sh
-RUN  chmod -R g+rwx "/usr/bin/local/"
 
 ARG JAVA_VERSION=17.0.12_7
-RUN set -x; apt-get update && \
-    apt-get install --no-install-recommends -y \
-    ca-certificates \
-    jq \
-    curl &&\
-    /usr/bin/local/jdk-download.sh
+RUN set -x; apt-get update \
+  && apt-get install --no-install-recommends -y \
+  ca-certificates \
+  jq \
+  curl \
+  && /usr/bin/local/jdk-download.sh && apt-get clean
 
 ENV PATH="/opt/jdk-${JAVA_VERSION}/bin:${PATH}"
 
@@ -46,22 +25,23 @@ ENV PATH="/opt/jdk-${JAVA_VERSION}/bin:${PATH}"
 # for now we include the full module path to maintain compatibility
 # while still saving space (approx 200mb from the full distribution)
 RUN case "$(jlink --version 2>&1)" in \
-      # jlink version 11 has less features than JDK17+
-      "11."*) set -- "--strip-debug" "--compress=2" ;; \
-      "17."*) set -- "--strip-java-debug-attributes" "--compress=2" ;; \
-      # the compression argument is different for JDK21
-      "21."*) set -- "--strip-java-debug-attributes" "--compress=zip-6" ;; \
-      *) echo "ERROR: unmanaged jlink version pattern" && exit 1 ;; \
-    esac; \
-    jlink \
-      "$1" \
-      "$2" \
-      --add-modules ALL-MODULE-PATH \
-      --no-man-pages \
-      --no-header-files \
-      --output /javaruntime
+  # jlink version 11 has less features than JDK17+
+  "11."*) set -- "--strip-debug" "--compress=2" ;; \
+  "17."*) set -- "--strip-java-debug-attributes" "--compress=2" ;; \
+  # the compression argument is different for JDK21
+  "21."*) set -- "--strip-java-debug-attributes" "--compress=zip-6" ;; \
+  *) echo "ERROR: unmanaged jlink version pattern" && exit 1 ;; \
+  esac; \
+  jlink \
+  "$1" \
+  "$2" \
+  --add-modules ALL-MODULE-PATH \
+  --no-man-pages \
+  --no-header-files \
+  --output /javaruntime
 
-FROM debian:"${DEBIAN_RELEASE}"
+# FROM bitnami/minideb
+FROM debian:"${DEBIAN_RELEASE}"-slim
 
 ARG user=jenkins
 ARG group=jenkins
@@ -75,53 +55,48 @@ ARG AGENT_WORKDIR="${JENKINS_AGENT_HOME}/agent"
 ENV AGENT_WORKDIR=${AGENT_WORKDIR}
 
 RUN groupadd -g ${gid} ${group} \
-    && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}" \
-    # Prepare subdirectories
-    && mkdir -p "${JENKINS_AGENT_HOME}/.ssh/" "${AGENT_WORKDIR}" "${JENKINS_AGENT_HOME}/.jenkins" \
-    # Make sure that user 'jenkins' own these directories and their content
-    && chown -R "${uid}":"${gid}" "${JENKINS_AGENT_HOME}" "${AGENT_WORKDIR}"
+  && useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}" \
+  # Prepare subdirectories
+  && mkdir -p "${JENKINS_AGENT_HOME}/.ssh/" "${AGENT_WORKDIR}" "${JENKINS_AGENT_HOME}/.jenkins" \
+  # Make sure that user 'jenkins' own these directories and their content
+  && chown -R "${uid}":"${gid}" "${JENKINS_AGENT_HOME}" "${AGENT_WORKDIR}"
 
 RUN apt-get update \
-    && apt-get install --no-install-recommends -y \
-        ca-certificates \
-        git-lfs \
-        less \
-        netcat-traditional \
-        openssh-server \
-        patch \
-        curl \
-        apt-transport-https \
-        ca-certificates \
-        gnupg \
-        wget \
-        lsb-release \
-        apt-transport-https \
-    && rm -rf /var/lib/apt/lists/*
-
-## install docker
-RUN apt-get update && \
-    apt-get install -y ca-certificates curl && \
-    install -m 0755 -d /etc/apt/keyrings && \
-    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
-    chmod a+r /etc/apt/keyrings/docker.asc && \
-    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo bookworm main) stable" | \
-    tee /etc/apt/sources.list.d/docker.list > /dev/null && \
-    apt-get update && \
-    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin 
-
-## Install trivy
-RUN wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add - && \
-        echo deb https://aquasecurity.github.io/trivy-repo/deb bookworm main | tee -a /etc/apt/sources.list.d/trivy.list && \
-        apt-get update && apt-get install trivy 
+  && apt-get install --no-install-recommends -y \
+  ca-certificates \
+  git-lfs \
+  less \
+  netcat-traditional \
+  openssh-server \
+  patch \
+  curl \
+  apt-transport-https \
+  gnupg \
+  wget \
+  lsb-release \
+  apt-transport-https \
+  && rm -rf /var/lib/apt/lists/* && apt-get clean && \
+  # install docker
+  install -m 0755 -d /etc/apt/keyrings && \
+  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
+  chmod a+r /etc/apt/keyrings/docker.asc && \
+  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo bookworm main) stable" | \
+  tee /etc/apt/sources.list.d/docker.list > /dev/null && \
+  apt-get update && \
+  apt-get install -y docker-ce docker-ce-cli containerd.io && apt-get clean &&\
+  # Install Trivy
+  wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add - && \
+  echo deb https://aquasecurity.github.io/trivy-repo/deb bookworm main | tee -a /etc/apt/sources.list.d/trivy.list && \
+  apt-get update && apt-get install trivy && apt-get clean
 
 # setup SSH server
 RUN sed -i /etc/ssh/sshd_config \
-        -e 's/#PermitRootLogin.*/PermitRootLogin no/' \
-        -e 's/#RSAAuthentication.*/RSAAuthentication yes/'  \
-        -e 's/#PasswordAuthentication.*/PasswordAuthentication no/' \
-        -e 's/#SyslogFacility.*/SyslogFacility AUTH/' \
-        -e 's/#LogLevel.*/LogLevel INFO/' && \
-    mkdir /var/run/sshd
+  -e 's/#PermitRootLogin.*/PermitRootLogin no/' \
+  -e 's/#RSAAuthentication.*/RSAAuthentication yes/'  \
+  -e 's/#PasswordAuthentication.*/PasswordAuthentication no/' \
+  -e 's/#SyslogFacility.*/SyslogFacility AUTH/' \
+  -e 's/#LogLevel.*/LogLevel INFO/' && \
+  mkdir /var/run/sshd
 
 # VOLUME directive must happen after setting up permissions and content
 VOLUME "${AGENT_WORKDIR}" "${JENKINS_AGENT_HOME}"/.jenkins "/tmp" "/run" "/var/run"
@@ -139,11 +114,3 @@ COPY setup-sshd /usr/local/bin/setup-sshd
 EXPOSE 22
 
 ENTRYPOINT ["setup-sshd"]
-
-LABEL \
-    org.opencontainers.image.vendor="Jenkins project" \
-    org.opencontainers.image.title="Official Jenkins SSH Agent Docker image" \
-    org.opencontainers.image.description="A Jenkins agent image which allows using SSH to establish the connection" \
-    org.opencontainers.image.url="https://www.jenkins.io/" \
-    org.opencontainers.image.source="https://github.com/jenkinsci/docker-ssh-agent" \
-    org.opencontainers.image.licenses="MIT"
